### PR TITLE
Chassis board new revision

### PR DESCRIPTION
**Pull request by LeftistTachyon**
Things added:
- Many more connectors (UART, SWD, actual power connector, yaw motor connectors, etc.)
- Comprehensive silkscreen
- A lot of LEDs (prepare to be blinded)
- Reasonable dimensions

TODO:
- [x] Generate BOM & IBOM
- [x] Put our names on it
- [x] ~~Implement watchdog circuit~~ for later years
- [x] Change C5 and C6 to be 0805 (Mouser doesn't have 0603)

### CODE REVIEW

**Review by Lakshay983 — CHANGES_REQUESTED** [review]
Fix merge conflicts :)

**Comment by Lakshay983** [comment]
I'm a huge oblong plane hater. Makes editing them horrible. There should be only be right angles in the shape you draw ideally.
image

**Comment by Lakshay983** [comment]
image
image
Can you do what is recommended on the datasheet for the SHDN pin. (tying Vin and SHDN with a 100k). Floating should work according to the datasheet as well, but I personally def prefer tying all pins to smth. It's only disabled when it's below 1.25V and there's an internal pullup but one extra resistor isn't rlly anything.

**Comment by Lakshay983** [comment]
image
put silkscreen labels here

**Comment by Lakshay983** [comment]
image
Make 19V a pour. Also change the name vout to like 19v or smth.

**Comment by Lakshay983** [comment]
This one isn't the most important thing, can u add 3D models for the xt30 and ur molex connector. It'll look hella clean once it's rendered.

Also make sure to add y'all's names to the board!

**Comment by LeftistTachyon** [comment]
> image Make 19V a pour. Also change the name vout to like 19v or smth.

subjective no change

**Comment by LeftistTachyon** [comment]
> This one isn't the most important thing, can u add 3D models for the xt30 and ur molex connector. It'll look hella clean once it's rendered.
> 
> Also make sure to add y'all's names to the board!

They're already there, you need to set your paths up correctly

**Comment by LeftistTachyon** [comment]
image
case and point

**Comment by LeftistTachyon** [comment]
> Fix merge conflicts :)

Done

**Comment by LeftistTachyon** [comment]
> image image Can you do what is recommended on the datasheet for the SHDN pin. (tying Vin and SHDN with a 100k). Floating should work according to the datasheet as well, but I personally def prefer tying all pins to smth. It's only disabled when it's below 1.25V and there's an internal pullup but one extra resistor isn't rlly anything.

Fixed

**Review by Lakshay983 — APPROVED** [review]
LGTM

Figure out da uart situation with Caleb
Add BOM + IBOM
Add y'all's names

**Comment by yuqipan** [comment]
Need to take in CAN2 signal and pass up to Turrent board in addition to taking in CAN1 (signals for gimble and chassis)  and Ref System CAN. CAN2 signal needs to be completely separate from CAN1. All CAN signals need to be passed up to the turret board.

**Comment by yuqipan** [comment]
Check that the CAN signals match up. Ex: dev board outputs CANL CANH from left to right to plug in properly into chassis board CAN needs to be CANH CANL from left to right. However, CAN2 is CANH CANL from left to right coming out of the dev board.

image

**Comment by LeftistTachyon** [comment]
> Check that the CAN signals match up. Ex: dev board outputs CANL CANH from left to right to plug in properly into chassis board CAN needs to be CANH CANL from left to right. However, CAN2 is CANH CANL from left to right coming out of the dev board.
> 
> image

done

**Pull request merged**
