### PR TITLE
Wiring Diagram

### PR DESCRIPTION
**Pull request by Lakshay983**
WIRES

### CODE REVIEW

**Comment by LeftistTachyon** [comment]
Is this [this wiring diagram](https://app.diagrams.net/#G1Zi-GqqWRVjdO2nXrK9KqYeAXQvQqBj6Z#%7B%22pageId%22%3A%22l9qn3NA8CEYEROPY9smo%22%7D)?

**Comment by Lakshay983** [comment]
> Is this [this wiring diagram](https://app.diagrams.net/#G1Zi-GqqWRVjdO2nXrK9KqYeAXQvQqBj6Z#%7B%22pageId%22%3A%22l9qn3NA8CEYEROPY9smo%22%7D)?

yeah

**Review by calebchalmers — CHANGES_REQUESTED** [review]
I updated the diagram with more info and the new proposal for VTM wiring

* Added CAN Id labels
* Added aviator wire through slip ring
* Added VTM and Speed Monitor Module
* Added misc Ref System components
* Removed brainrot (I'm sorry the file was too big for git :sob: )
* Switched Orin Nano from UART to CAN2

Requested changes: We need add a control pin for watchdog/motor shutoff ability once that's figured out

**Review by LeftistTachyon — APPROVED** [review]
Since we aren't going to make any significant changes in the harness (not by the looks of it), I think this is good to move forward.

(This is since it's unlikely that we'll get that kill switch for motors)

**Pull request closed without merging**
