### PR TITLE
Create chassis board

### PR DESCRIPTION
**Pull request by LeftistTachyon**
TODO:
- [x] Add 5V buck converter
- [x] Add all data in connectors
- [x] Add data out connector
- [x] Add all passthrough power inputs
- [x] Wire all connectors together

### CODE REVIEW

**Comment by LeftistTachyon** [comment]
@Lakshay983 see above commits; added test points & part number

Currently am too busy to actually route the bucks, but you can reference the old designs (with the old dimensions) to see generally what ideas I had

**Comment by Lakshay983** [comment]
image

**Review by Lakshay983 — COMMENTED** [review]
Current limiting resistors for indicator leds has a big margin from what it should be when you calc it.
(24 - 2)/.02
(19 - 2)/.02

**Review by Lakshay983 — CHANGES_REQUESTED** [review]
A couple nitpicks:
- Make sure your components are aligned. Select components that are aligned with each other, right click -> align/distribute -> select relevant command
- Please make the pours neater shapes (corners aligned and such)
- Where edge cut layer
- Please delete all the old dimensions and put new dimensions on there. Make sure you draw the dimensions on the User.drawings layer
- Talk to mech and ask where they want the holes for the Chassis board and delete the other holes that you don't need.
- There are a few redundant traces (like C2), you can go to Tools -> Cleanup Tracks and Vias to clean those up

There are a bunch of DRC errors, most of them are because things are too close together (like those can test points), edge cuts, and other clearance violations

In a previous review I asked to change the resistor values for the LEDs. The way you calculate the values you need is by doing (Vin - Vf)/(Id)
Vin -> Your input voltage
Vf -> The forward voltage is the voltage needed to turn the LED on
Id -> The current needed through the led at the forward voltage
You can find Vf and Id in the LED datasheet. Most of the values are close but the error is a bit too high for comfort.

19V trace next to the can lines makes me scared (i'd recommend making the 19V trace a pour on the bottom layer).
Screenshot 2023-12-20 at 12 20 58 AM

**Pull request closed without merging**
